const express = require("express");
const router = express.Router();
const { protect, authorize } = require("../middlewares/authMiddleware");
const voucherController = require("../controllers/voucherController");

/**
 * @swagger
 * tags:
 *   name: Vouchers
 *   description: Voucher management (phase 1)
 */

/**
 * @swagger
 * /api/vouchers:
 *   post:
 *     summary: Create voucher
 *     tags: [Vouchers]
 *     description: Voucher code is auto-generated by the system using format VC-YYMMDD-Type (Type = FIX or PCT).
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - discount_type
 *               - discount_value
 *               - valid_from
 *               - valid_to
 *             properties:
 *               description:
 *                 type: string
 *                 example: "Voucher for weekend promo"
 *               discount_type:
 *                 type: string
 *                 enum: [PERCENT, FIXED]
 *                 example: PERCENT
 *               discount_value:
 *                 type: number
 *                 example: 20
 *               max_discount:
 *                 type: number
 *                 nullable: true
 *                 example: 100000
 *               min_booking_value:
 *                 type: number
 *                 example: 200000
 *               valid_from:
 *                 type: string
 *                 format: date-time
 *               valid_to:
 *                 type: string
 *                 format: date-time
 *               usage_limit:
 *                 type: integer
 *                 nullable: true
 *                 example: 500
 *               is_active:
 *                 type: boolean
 *                 example: true
 *     responses:
 *       201:
 *         description: Voucher created successfully (response includes generated code in VC-YYMMDD-Type format)
 *     security:
 *       - bearerAuth: []
 *   get:
 *     summary: Get vouchers list
 *     tags: [Vouchers]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: Voucher list retrieved successfully
 *       401:
 *         description: Unauthorized
 */
router.post("/", protect, authorize("admin"), voucherController.createVoucher);
router.get("/", protect, voucherController.getVouchers);

/**
 * @swagger
 * /api/vouchers/code/{code}:
 *   get:
 *     summary: Get voucher by code
 *     tags: [Vouchers]
 *     security:
 *       - bearerAuth: []
 */
router.get("/code/:code", protect, authorize("admin"), voucherController.getVoucherByCode);

/**
 * @swagger
 * /api/vouchers/{id}:
 *   get:
 *     summary: Get voucher by id
 *     tags: [Vouchers]
 *     security:
 *       - bearerAuth: []
 *   put:
 *     summary: Update voucher
 *     tags: [Vouchers]
 *     security:
 *       - bearerAuth: []
 */
router.get("/:id", protect, authorize("admin"), voucherController.getVoucherById);
router.put("/:id", protect, authorize("admin"), voucherController.updateVoucher);

/**
 * @swagger
 * /api/vouchers/{id}/activate:
 *   patch:
 *     summary: Activate voucher
 *     tags: [Vouchers]
 *     security:
 *       - bearerAuth: []
 */
router.patch("/:id/activate", protect, authorize("admin"), voucherController.activateVoucher);

/**
 * @swagger
 * /api/vouchers/{id}/deactivate:
 *   patch:
 *     summary: Deactivate voucher
 *     tags: [Vouchers]
 *     security:
 *       - bearerAuth: []
 */
router.patch("/:id/deactivate", protect, authorize("admin"), voucherController.deactivateVoucher);

module.exports = router;
