const NOTIFICATION_TYPES = ["BOOKING", "PAYMENT", "PROMOTION", "SYSTEM", "IDENTITY"];

const NOTIFICATION_EVENT_CODES = [
  "BOOKING_CANCELLED",
  "BOOKING_CHECKIN",
  "BOOKING_CHECKOUT",
  "BOOKING_AUTO_CHECKIN",
  "BOOKING_AUTO_CHECKOUT",
  "BOOKING_NO_SHOW",
  "BOOKING_REMINDER",
  "PAYMENT_SUCCESS",
  "PAYMENT_REFUND_SUCCESS",
  "PROMOTION_BROADCAST",
  "SYSTEM_TEST",
  "SYSTEM_GENERAL",
  "IDENTITY_VERIFIED",
];

const DELIVERY_STATUSES = ["PENDING", "SENT", "FAILED", "SKIPPED_NO_TOKEN"];

module.exports = {
  NOTIFICATION_TYPES,
  NOTIFICATION_EVENT_CODES,
  DELIVERY_STATUSES,
};
