module.exports = {
  User: require("./User"),
  Location: require("./Location"),
  PodCluster: require("./PodCluster"),
  Pod: require("./Pod"),
  PodAmenity: require("./PodAmenity"),
  Door: require("./Door"),
  PodDevice: require("./PodDevice"),
  PodQrCode: require("./PodQrCode"),
  Booking: require("./Bookings"),
  BookingOrder: require("./BookingOrder"),
  BookingSlot: require("./BookingSlot"),
  BookingAccessSession: require("./BookingAccessSession"),
  OnlineKey: require("./OnlineKey"),
  Incident: require("./Incidents"),
  Payment: require("./Payment"),
  TimeSlot: require("./TimeSlot"),
  Item: require("./Item"),
  Warehouse: require("./Warehouse"),
  LocationWarehouse: require("./LocationWarehouse"),
  InventoryStock: require("./InventoryStock"),
  InventoryCheckoutLog: require("./InventoryCheckoutLog"),
  PodItem: require("./PodItem"),
  StaffShift: require("./StaffShift"),
  LocationShift: require("./LocationShift"),
  StaffShiftAssignment: require("./StaffShiftAssignment"),
  StaffAttendanceLog: require("./StaffAttendanceLog"),
};